backend:
  name: github
  repo: camdunne/gatsby-bakery-site

media_folder: static/assets
public_folder: /assets

collections:
  - name: "item"
    label: "Item"
    folder: "content/item"
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: price, label: Price, widget: number, valueType: float, min: 0, step: 0.01 }
      - { name: image, label: Image, widget: image }
      - { name: description, label: Description, widget: markdown }